# Generated by Django 3.2.18 on 2023-12-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_manipulation', models.DateField(verbose_name='дата проведения манипуляции')),
            ],
        ),
        migrations.CreateModel(
            name='Lab_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='номер группы')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.TextField(blank=True, verbose_name='Должноcть'),
        ),
        migrations.AddField(
            model_name='equine',
            name='sex',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='manipulation',
            name='volume',
            field=models.CharField(blank='True', max_length=200, verbose_name='Объем, мл'),
        ),
        migrations.AlterField(
            model_name='equine',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Кличка'),
        ),
    ]
