# Generated by Django 3.2.18 on 2023-12-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0002_auto_20231204_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab_group',
            name='title',
            field=models.IntegerField(verbose_name='номер группы'),
        ),
    ]
