# Generated by Django 3.2.18 on 2023-12-04 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0005_auto_20231204_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab_group',
            name='antigen',
            field=models.OneToOneField(blank='True', null='True', on_delete=django.db.models.deletion.DO_NOTHING, related_name='antigen_group', to='horses.antigen'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='lab_group',
            name='equine',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.DO_NOTHING, related_name='equine_group', to='horses.equine'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='manipulation',
            name='employee',
            field=models.ManyToManyField(related_name='action_taken', to='horses.Employee'),
        ),
        migrations.CreateModel(
            name='Restriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Названия ограничений')),
                ('reason', models.TextField(blank=True, default='', verbose_name='Описание причины ограничения')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='who_identified_restriction', to='horses.employee')),
                ('equine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='restriction_to_use', to='horses.equine')),
            ],
        ),
        migrations.CreateModel(
            name='Cure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Названия метода лечения')),
                ('reason', models.TextField(blank=True, default='', verbose_name='Описание способа лечения')),
                ('equine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescribed_treatment', to='horses.equine')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='therapist', to='horses.employee')),
            ],
        ),
    ]
