# Generated by Django 3.2.18 on 2023-12-05 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0006_auto_20231204_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab_group',
            name='antigen',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.DO_NOTHING, related_name='antigen_group', to='horses.antigen'),
        ),
        migrations.RemoveField(
            model_name='lab_group',
            name='equine',
        ),
        migrations.AddField(
            model_name='lab_group',
            name='equine',
            field=models.ManyToManyField(blank='True', null='True', related_name='equine_group', to='horses.Equine'),
            preserve_default='True',
        ),
    ]
