# Generated by Django 3.2.18 on 2023-12-05 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0007_auto_20231205_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab_group',
            name='equine',
        ),
        migrations.AddField(
            model_name='lab_group',
            name='equine',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.DO_NOTHING, related_name='equine_group', to='horses.equine'),
            preserve_default='True',
        ),
    ]
