# Generated by Django 3.2.18 on 2023-12-05 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0008_auto_20231205_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab_group',
            name='equine',
        ),
        migrations.AddField(
            model_name='equine',
            name='lab_group',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.DO_NOTHING, related_name='equine', to='horses.lab_group'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='lab_group',
            name='title',
            field=models.IntegerField(verbose_name='название группы'),
        ),
    ]
