# Generated by Django 3.2.18 on 2023-12-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0009_auto_20231205_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab_group',
            name='employee',
            field=models.ManyToManyField(blank='True', null='True', related_name='serviced_group', to='horses.Employee'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='equine',
            name='date_of_death',
            field=models.DateField(blank=True, null=True, verbose_name='дата выбытия'),
        ),
    ]
