# Generated by Django 3.2.18 on 2023-12-05 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0010_auto_20231205_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab_group',
            name='employee',
        ),
        migrations.AddField(
            model_name='lab_group',
            name='employee',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.DO_NOTHING, related_name='serviced_group', to='horses.employee'),
            preserve_default='True',
        ),
    ]
