# Generated by Django 3.2.18 on 2023-12-05 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0012_calendar_employe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equine',
            options={'ordering': ['title'], 'verbose_name': 'Фотография достопримечательности', 'verbose_name_plural': 'Фотографии достопримечательности'},
        ),
    ]
