# Generated by Django 3.2.18 on 2023-12-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0013_alter_equine_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equine',
            options={'ordering': ['title'], 'verbose_name': 'Лошадь-продуцент', 'verbose_name_plural': 'Лошади-продуценты'},
        ),
        migrations.RemoveField(
            model_name='lab_group',
            name='employee',
        ),
        migrations.AddField(
            model_name='lab_group',
            name='employee',
            field=models.ManyToManyField(blank='True', null='True', related_name='serviced_group', to='horses.Employee'),
            preserve_default='True',
        ),
    ]
