# Generated by Django 3.2.18 on 2023-12-05 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0014_auto_20231205_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='antigen',
            options={'ordering': ['title'], 'verbose_name': 'Антиген', 'verbose_name_plural': 'Антигены'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['title'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='lab_group',
            options={'ordering': ['title'], 'verbose_name': 'Лабораторная группа', 'verbose_name_plural': 'Лабораторные группы'},
        ),
    ]
