# Generated by Django 3.2.18 on 2023-12-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0015_auto_20231205_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manipulation',
            name='employee',
        ),
        migrations.AddField(
            model_name='employee',
            name='manipulate_acts',
            field=models.ManyToManyField(related_name='employees', to='horses.Manipulation'),
        ),
    ]
