# Generated by Django 3.2.18 on 2023-12-05 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0017_auto_20231205_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='serviced_group',
            new_name='serviced_groups',
        ),
    ]
