# Generated by Django 3.2.18 on 2023-12-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0018_rename_serviced_group_employee_serviced_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='serviced_groups',
        ),
        migrations.AddField(
            model_name='lab_group',
            name='employees',
            field=models.ManyToManyField(blank='True', null='True', related_name='serviced_group', to='horses.Employee'),
            preserve_default='True',
        ),
    ]
