# Generated by Django 3.2.18 on 2023-12-05 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0019_auto_20231205_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='antigen',
            name='production_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата приготовления'),
        ),
        migrations.AlterField(
            model_name='equine',
            name='lab_group',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.DO_NOTHING, related_name='equine', to='horses.lab_group', verbose_name='Лабораторная группа'),
        ),
        migrations.AlterField(
            model_name='lab_group',
            name='antigen',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.DO_NOTHING, related_name='antigen_group', to='horses.antigen', verbose_name='Используемый материал для иммунизации'),
        ),
    ]
