# Generated by Django 3.2.18 on 2023-12-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0022_alter_lab_group_employees'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendar',
            options={'ordering': ['date_manipulation', 'groups'], 'verbose_name': 'Дата проведения процедуры', 'verbose_name_plural': 'Даты проведения процедуры'},
        ),
        migrations.AlterModelOptions(
            name='cure',
            options={'ordering': ['title'], 'verbose_name': 'Лечение', 'verbose_name_plural': 'Лечение'},
        ),
        migrations.AlterModelOptions(
            name='restriction',
            options={'ordering': ['title'], 'verbose_name': 'Ограничение по эксплуатации', 'verbose_name_plural': 'Ограничения по эксплуатации'},
        ),
        migrations.RemoveField(
            model_name='restriction',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='restriction',
            name='equine',
        ),
        migrations.AddField(
            model_name='restriction',
            name='equine',
            field=models.ManyToManyField(related_name='restriction_to_use', to='horses.Equine', verbose_name='Кличка лошади'),
        ),
    ]
