# Generated by Django 3.2.18 on 2023-12-07 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0024_alter_manipulation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab_group',
            name='antigen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='antigen_group', to='horses.antigen', verbose_name='Используемый материал для иммунизации'),
        ),
    ]
