# Generated by Django 3.2.18 on 2023-12-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0025_alter_lab_group_antigen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='equine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='изображение'),
        ),
    ]
