# Generated by Django 3.2.18 on 2024-04-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0026_auto_20231211_1020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equine',
            options={'ordering': ['lab_group', 'title'], 'verbose_name': 'Лошадь-продуцент', 'verbose_name_plural': 'Лошади-продуценты'},
        ),
        migrations.AddField(
            model_name='equine',
            name='breed',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Порода'),
        ),
        migrations.AddField(
            model_name='equine',
            name='coat_color',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Масть лошади'),
        ),
        migrations.AddField(
            model_name='equine',
            name='purchase_place',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Место приобретения'),
        ),
    ]
