# Generated by Django 3.2.18 on 2024-04-19 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0027_auto_20240419_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equine',
            name='anamnesis',
        ),
    ]
