# Generated by Django 3.2.18 on 2024-04-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0028_remove_equine_anamnesis'),
    ]

    operations = [
        migrations.AddField(
            model_name='equine',
            name='serum_activity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
