# Generated by Django 3.2.18 on 2024-04-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0029_equine_serum_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equine',
            name='serum_activity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Активность сыворотки'),
        ),
        migrations.AlterField(
            model_name='equine',
            name='sex',
            field=models.CharField(choices=[('M', 'Жеребец'), ('F', 'Кобыла'), ('G', 'Мерин')], db_index=True, default='M', max_length=4, verbose_name='Пол'),
        ),
    ]
