# Generated by Django 3.2.18 on 2024-04-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0030_auto_20240419_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antigen',
            name='production_date',
        ),
        migrations.AddField(
            model_name='manipulation',
            name='volume_measure',
            field=models.CharField(blank='True', choices=[('ML', 'Объем, мл'), ('L', 'Объем, л'), ('C', 'млрд микробных клеток')], db_index=True, default='ML', max_length=200, verbose_name='Едииница измерения'),
        ),
        migrations.AlterField(
            model_name='manipulation',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Количество'),
        ),
    ]
