# Generated by Django 3.2.18 on 2024-04-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0031_auto_20240419_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab_group',
            name='title',
            field=models.CharField(max_length=200, verbose_name='название группы'),
        ),
    ]
