# Generated by Django 3.2.18 on 2024-04-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0033_auto_20240422_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='equine',
            name='in_operation',
            field=models.BooleanField(default=True, verbose_name='используется ли лошадь'),
        ),
    ]
