# Generated by Django 3.2.18 on 2024-04-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0034_equine_in_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab_group',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
