# Generated by Django 3.2.18 on 2024-04-30 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0036_auto_20240430_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='groups',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='horses.lab_group', verbose_name='Рабочая группа'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='manipulations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='manipulation_date', to='horses.manipulation'),
        ),
    ]
