# Generated by Django 3.2.18 on 2024-04-30 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0037_auto_20240430_0748'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restriction',
            options={'ordering': ['begin_restriction'], 'verbose_name': 'Ограничение по эксплуатации', 'verbose_name_plural': 'Ограничения по эксплуатации'},
        ),
        migrations.RemoveField(
            model_name='antigen',
            name='description_long',
        ),
        migrations.RemoveField(
            model_name='antigen',
            name='description_short',
        ),
        migrations.AddField(
            model_name='antigen',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='manipulations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='manipulation_date', to='horses.manipulation', verbose_name='Название манипуляции'),
        ),
        migrations.AlterField(
            model_name='manipulation',
            name='volume_measure',
            field=models.CharField(blank='True', choices=[('мл', 'мл'), ('л', 'л'), ('млрд клеток', 'млрд клеток')], db_index=True, default='ML', max_length=200, verbose_name='Единица измерения'),
        ),
    ]
