# Generated by Django 3.2.18 on 2024-05-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0038_auto_20240430_1111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equine',
            options={'ordering': ['lab_group', 'title', 'commissioning_date'], 'verbose_name': 'Лошадь-продуцент', 'verbose_name_plural': 'Лошади-продуценты'},
        ),
        migrations.AddField(
            model_name='antigen',
            name='volume_measure',
            field=models.CharField(blank='True', choices=[('мл', 'мл'), ('л', 'л'), ('млрд клеток', 'млрд клеток')], db_index=True, default='мл', max_length=200, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='equine',
            name='breed',
            field=models.CharField(default='Беспородная', max_length=200, verbose_name='Порода'),
        ),
        migrations.AlterField(
            model_name='equine',
            name='purchase_place',
            field=models.CharField(default='Неизвестно', max_length=200, verbose_name='Место приобретения'),
        ),
        migrations.AlterField(
            model_name='equine',
            name='serum_activity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Активность сыворотки'),
        ),
        migrations.AlterField(
            model_name='lab_group',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='manipulation',
            name='volume_measure',
            field=models.CharField(blank='True', choices=[('мл', 'мл'), ('л', 'л'), ('млрд клеток', 'млрд клеток')], db_index=True, default='мл', max_length=200, verbose_name='Единица измерения'),
        ),
    ]
